name: skeletonizer
description: Converts already built widgets into skeleton loaders with no extra effort.
version: 1.1.1
homepage: https://github.com/Milad-Akarie/skeletonizer
screenshots:
  - description: 'Example of skeletonizer in action.'
    path: art/screen_shot_1.png
topics:
  - skeleton
  - shimmer-loading
  - skeleton-loader
  - loading

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  alchemist: 0.7.0


flutter:
  uses-material-design: true

